name: UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Java 25
        uses: actions/checkout@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Run tests
        run: mvn -B test